FROM nnurphy/deployment

ARG PHP_VERSION=5.6
ENV PHP_PGKS \
        php${PHP_VERSION} \
        php${PHP_VERSION}-fpm \
        php${PHP_VERSION}-cli \
        php${PHP_VERSION}-common \
        php${PHP_VERSION}-curl \
        php${PHP_VERSION}-gd \
        php${PHP_VERSION}-json \
        php${PHP_VERSION}-mbstring \
        php${PHP_VERSION}-mysql \
        php${PHP_VERSION}-xml \
        php${PHP_VERSION}-zip \
        php${PHP_VERSION}-bcmath

RUN set -eux \
  ; curl -sL https://packages.sury.org/php/apt.gpg | apt-key add - \
  ; echo "deb https://packages.sury.org/php/ buster main"  \
        | tee /etc/apt/sources.list.d/php.list \
  ; apt-get update \
  ; apt-get install -y --no-install-recommends $PHP_PGKS \
  ; apt-get autoremove -y && apt-get clean -y && rm -rf /var/lib/apt/lists/* \
  ; ln -sf /usr/sbin/php-fpm${PHP_VERSION} /usr/sbin/php-fpm

COPY docker-nginx-default /etc/nginx/conf.d/default.conf
COPY services.d/php-fpm /etc/services.d/php-fpm