FROM 7.2.24-fpm-buster

# sodium was built as a shared module (so that it can be replaced later if so desired), so let's enable it too (https://github.com/docker-library/php/issues/598)
RUN docker-php-ext-enable sodium

# temporary "freetype-config" workaround for https://github.com/docker-library/php/issues/865 (https://bugs.php.net/bug.php?id=76324)
RUN { echo '#!/bin/sh'; echo 'exec pkg-config "$@" freetype2'; } > /usr/local/bin/freetype-config && chmod +x /usr/local/bin/freetype-config

RUN apk add --no-cache \
        libfreetype6-dev \
        libjpeg62-turbo-dev \
        libpng-dev \
    && docker-php-ext-install -j$(nproc) iconv \
    && docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
    && docker-php-ext-install -j$(nproc) gd \
	&& rm -rf /var/lib/apt/lists/*

RUN set -eux \
  ; pecl install redis-4.0.1 \
  ; pecl install xdebug-2.6.0 \
  ; docker-php-ext-enable redis xdebug \
  ; docker-php-ext-install mysqli && docker-php-ext-enable mysqli \
  ; docker-php-ext-install mysql && docker-php-ext-enable mysql \
  ; docker-php-ext-install pdo && docker-php-ext-enable pdo \
  ; docker-php-ext-install pdo_mysql && docker-php-ext-enable pdo_mysql \
  #; docker-php-ext-install curl && docker-php-ext-enable curl \
  #; docker-php-ext-install bz2 && docker-php-ext-enable bz2 \
  ; docker-php-ext-install mbstring && docker-php-ext-enable mbstring \
  ; docker-php-ext-install bcmath && docker-php-ext-enable bcmath \
  ; docker-php-ext-install zip && docker-php-ext-enable zip
