#!/usr/bin/with-contenv sh
if [ ! -z $PHP_UPLOAD_MAX_FILESIZE ]; then
    sed -i 's!\(upload_max_filesize =\).*!\1 '"$PHP_UPLOAD_MAX_FILESIZE"'!g' /etc/php/*/fpm/php.ini
fi


echo >&2 "starting php-fpm"

exec /usr/sbin/php-fpm 2>&1